### ISSUE TITLE
Minimum Version Doesn't Apply to Tasks.py

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/cookiecutter-nautobot-app#189]
### Environment

* Python version:  3.11.6
* cookiecutter-nautobot-app template version:  Develop branch from 2024-10-15

### Observed Behavior

```
 => [nautobot] resolving provenance for metadata file                                                                                                                                      0.0s
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/cli/__init__.py", line 292, in main
    load_settings(args.config_path)
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
    _preprocess_settings(module, config_path)
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
    load_plugins(settings)
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
    load_plugin(plugin_name, settings)
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/plugins/utils.py", line 87, in load_plugin
    plugin_config.validate(settings.PLUGINS_CONFIG[plugin_name], settings.VERSION)
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/plugins/__init__.py", line 225, in validate
    raise PluginImproperlyConfigured(
nautobot.extras.plugins.exceptions.PluginImproperlyConfigured: Plugin job_testing requires Nautobot minimum version 2.3.6
```

### Expected Behavior

Expected to build with the latest version of Nautobot

### Steps to Reproduce

1. Bake a cookie
2. Set minimum Nautobot version to 2.3.6 (today's base)
3. Run `invoke makemigrations`

**Comment by gsnider2195** [comment]
Fix is to set `tasks.py` `nautobot_ver` to the greater of `2.3.11` (or something) or the `minimum_nautobot_ver` selected on bake
